# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/winners/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('affiliation', models.TextField()),
                ('country', models.CharField(max_length=70)),
                ('short_cv', models.CharField(max_length=200)),
                ('award_time', models.DateTimeField()),
                ('award_venue', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'International Winner',
            },
        ),
        migrations.CreateModel(
            name='InternationalWinnerAbstract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.TextField(blank=True, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
                ('method', models.TextField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akp.InternationalWinner', unique=True)),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NationalWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/winners/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('affiliation', models.TextField()),
                ('country', models.CharField(max_length=70)),
                ('short_cv', models.CharField(max_length=200)),
                ('award_time', models.DateTimeField()),
                ('award_venue', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'National Winner',
            },
        ),
        migrations.CreateModel(
            name='NationalWinnerAbstract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.TextField(blank=True, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
                ('method', models.TextField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akp.NationalWinner', unique=True)),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
    ]
